### ISSUE TITLE
nVidia 436.30 driver & ссminer not compatible.

### ISSUE THREAD

**Issue by FelixVVV** [zcoinofficial/ccminer#54]
After updating nVidia drivers to version 436.30, the following problems occur:
1. On a computer with one video card - the ccminer process constantly loads the processor by 25%, mining is not interrupted.
2. On a rig - the ccminer process constantly loads the processor by 100%, mining is interrupted (CUDA memory allocation error ), when pool find a block or when miner incrementing extra nonce.
(tested on versions 1.2.2, 1.2.1, 1.1.26).

Driver rollback to 431.86 solves problems, but this is a temporary solution.

**Comment by djm34** [comment]
as far as I know the problem (which affects all miners, not only ccminer) has been solved in the latest driver.

**Comment by FelixVVV** [comment]
Driver 436.30 is the latest driver, the problem is not solved.

**Comment by FelixVVV** [comment]
Latest 436.48 game ready driver -  the problem is not solved.

**Comment by djm34** [comment]
I haven't had time to look into it, for the moment the best move is probably to use an older version. 
Also it isn't clear what it will be possible to do.

**Comment by djm34** [comment]
I run a few test with most recent drivers and indeed it is pretty bad in terms of cpu usage (performance don't seem too much affected if there is only one card on the system, but with 2 performance are degraded). 
This is more a choice on the nvidia part to do the optimization toward gaming instead of cuda application. However, they also added a new set of driver: Nvidia Studio Driver (431.86) which seems the drivers which should now be used. In itself it makes sense since they are optimized for GPU application (to which miners belong). So it is probably the way to go

**Comment by FelixVVV** [comment]
Problem solved in latest game ready drivers 441.08

**Comment by djm34** [comment]
yes I noticed, the 2 last 441.08 and 440.97 have been working normally
